// Code generated by gogs. DO NOT EDIT.
package message

import (
	"github.com/metagogs/gogs/session"
	"github.com/szpnygo/gtc/server/model"
)

func SendOffer(s *session.Session, in *model.Offer) error {
	return s.SendMessage(in, "Offer")
}

func SendAnswer(s *session.Session, in *model.Answer) error {
	return s.SendMessage(in, "Answer")
}

func SendCandidate(s *session.Session, in *model.Candidate) error {
	return s.SendMessage(in, "Candidate")
}

func SendListRoom(s *session.Session, in *model.ListRoom) error {
	return s.SendMessage(in, "ListRoom")
}

func SendListRoomResponse(s *session.Session, in *model.ListRoomResponse) error {
	return s.SendMessage(in, "ListRoomResponse")
}

func SendJoinRoom(s *session.Session, in *model.JoinRoom) error {
	return s.SendMessage(in, "JoinRoom")
}

func SendJoinRoomSuccess(s *session.Session, in *model.JoinRoomSuccess) error {
	return s.SendMessage(in, "JoinRoomSuccess")
}

func SendJoinRoomNotify(s *session.Session, in *model.JoinRoomNotify) error {
	return s.SendMessage(in, "JoinRoomNotify")
}

func SendLeaveRoom(s *session.Session, in *model.LeaveRoom) error {
	return s.SendMessage(in, "LeaveRoom")
}

func SendLeaveRoomNotify(s *session.Session, in *model.LeaveRoomNotify) error {
	return s.SendMessage(in, "LeaveRoomNotify")
}

func SendListRoomUsers(s *session.Session, in *model.ListRoomUsers) error {
	return s.SendMessage(in, "ListRoomUsers")
}

func SendListRoomUsersResponse(s *session.Session, in *model.ListRoomUsersResponse) error {
	return s.SendMessage(in, "ListRoomUsersResponse")
}
