// Code generated by gogs. DO NOT EDIT.
package model

import (
	"context"
	"reflect"

	"github.com/metagogs/gogs"
	"github.com/metagogs/gogs/component"
	"github.com/metagogs/gogs/packet"
	"github.com/metagogs/gogs/session"
)

func RegisterAllComponents(s *gogs.App, srv Component) {
	registerGTCServerComponent(s, srv)

}

func registerGTCServerComponent(s *gogs.App, srv Component) {
	s.RegisterComponent(_GTCServerComponentDesc, srv)
}

type Component interface {
	Offer(ctx context.Context, s *session.Session, in *Offer)

	Answer(ctx context.Context, s *session.Session, in *Answer)

	Candidate(ctx context.Context, s *session.Session, in *Candidate)

	ListRoom(ctx context.Context, s *session.Session, in *ListRoom)

	JoinRoom(ctx context.Context, s *session.Session, in *JoinRoom)

	LeaveRoom(ctx context.Context, s *session.Session, in *LeaveRoom)

	ListRoomUsers(ctx context.Context, s *session.Session, in *ListRoomUsers)
}

func _GTCServerComponent_Offer_Handler(srv interface{}, ctx context.Context, sess *session.Session, in interface{}) {
	srv.(Component).Offer(ctx, sess, in.(*Offer))
}

func _GTCServerComponent_Answer_Handler(srv interface{}, ctx context.Context, sess *session.Session, in interface{}) {
	srv.(Component).Answer(ctx, sess, in.(*Answer))
}

func _GTCServerComponent_Candidate_Handler(srv interface{}, ctx context.Context, sess *session.Session, in interface{}) {
	srv.(Component).Candidate(ctx, sess, in.(*Candidate))
}

func _GTCServerComponent_ListRoom_Handler(srv interface{}, ctx context.Context, sess *session.Session, in interface{}) {
	srv.(Component).ListRoom(ctx, sess, in.(*ListRoom))
}

func _GTCServerComponent_JoinRoom_Handler(srv interface{}, ctx context.Context, sess *session.Session, in interface{}) {
	srv.(Component).JoinRoom(ctx, sess, in.(*JoinRoom))
}

func _GTCServerComponent_LeaveRoom_Handler(srv interface{}, ctx context.Context, sess *session.Session, in interface{}) {
	srv.(Component).LeaveRoom(ctx, sess, in.(*LeaveRoom))
}

func _GTCServerComponent_ListRoomUsers_Handler(srv interface{}, ctx context.Context, sess *session.Session, in interface{}) {
	srv.(Component).ListRoomUsers(ctx, sess, in.(*ListRoomUsers))
}

var _GTCServerComponentDesc = component.ComponentDesc{
	ComonentName:   "GTCServerComponent",
	ComponentIndex: 1, // equeal to module index
	ComponentType:  (*Component)(nil),
	Methods: []component.ComponentMethodDesc{
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 1), // 0x810001 8454145
			FieldType:   reflect.TypeOf(Offer{}),
			Handler:     _GTCServerComponent_Offer_Handler,
			FiledHanler: func() interface{} {
				return new(Offer)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 2), // 0x810002 8454146
			FieldType:   reflect.TypeOf(Answer{}),
			Handler:     _GTCServerComponent_Answer_Handler,
			FiledHanler: func() interface{} {
				return new(Answer)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 3), // 0x810003 8454147
			FieldType:   reflect.TypeOf(Candidate{}),
			Handler:     _GTCServerComponent_Candidate_Handler,
			FiledHanler: func() interface{} {
				return new(Candidate)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 4), // 0x810004 8454148
			FieldType:   reflect.TypeOf(ListRoom{}),
			Handler:     _GTCServerComponent_ListRoom_Handler,
			FiledHanler: func() interface{} {
				return new(ListRoom)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 5), // 0x810005 8454149
			FieldType:   reflect.TypeOf(ListRoomResponse{}),
			Handler:     nil,
			FiledHanler: func() interface{} {
				return new(ListRoomResponse)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 6), // 0x810006 8454150
			FieldType:   reflect.TypeOf(JoinRoom{}),
			Handler:     _GTCServerComponent_JoinRoom_Handler,
			FiledHanler: func() interface{} {
				return new(JoinRoom)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 7), // 0x810007 8454151
			FieldType:   reflect.TypeOf(JoinRoomSuccess{}),
			Handler:     nil,
			FiledHanler: func() interface{} {
				return new(JoinRoomSuccess)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 8), // 0x810008 8454152
			FieldType:   reflect.TypeOf(JoinRoomNotify{}),
			Handler:     nil,
			FiledHanler: func() interface{} {
				return new(JoinRoomNotify)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 9), // 0x810009 8454153
			FieldType:   reflect.TypeOf(LeaveRoom{}),
			Handler:     _GTCServerComponent_LeaveRoom_Handler,
			FiledHanler: func() interface{} {
				return new(LeaveRoom)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 10), // 0x81000a 8454154
			FieldType:   reflect.TypeOf(LeaveRoomNotify{}),
			Handler:     nil,
			FiledHanler: func() interface{} {
				return new(LeaveRoomNotify)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 11), // 0x81000b 8454155
			FieldType:   reflect.TypeOf(ListRoomUsers{}),
			Handler:     _GTCServerComponent_ListRoomUsers_Handler,
			FiledHanler: func() interface{} {
				return new(ListRoomUsers)
			},
		},
		{
			MethodIndex: packet.CreateAction(packet.ServicePacket, 1, 12), // 0x81000c 8454156
			FieldType:   reflect.TypeOf(ListRoomUsersResponse{}),
			Handler:     nil,
			FiledHanler: func() interface{} {
				return new(ListRoomUsersResponse)
			},
		},
	},
}
